apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo2
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
        version: v2
    spec:
      containers:
      - name: demo
        image: akihikokuroda/demo2
        imagePullPolicy: Always
        ports:
        - containerPort: 3000